version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: download dependency
          environment: 
            USER_SECRET: USER_SECRET
          command: npm ci
      - run: npm test
