version: 2
jobs:
  build:
    docker:
      - image: node:18.12.1
    steps:
      - checkout
      - run: npm install
      - run: npx babel src --out-dir lib
      - run: npx jest
      - run: nyc report --reporter=text-lcov | coveralls