version: 2
jobs:
  build:
    docker:
      - image: circleci/node:18.12.1
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: nyc report --reporter=text-lcov | coveralls