version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment: 
        USER_SECRET: USER_SECRET
    steps:
      - checkout
      - run: npm install
      - run: npm test
