version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 
          name: Install dependencies
          commands: |
            npm install
      - run:
          name: Run tests
          commands: |
            npm test
      - store_test_result:
          path: test_results
      - store_artifacts:
          path: test_results
workflows:  
  build_test:
    jobs:
      - run_tests