version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run : make test-coverage
      - run: npm test
      - coveralls/upload
