version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: download dependency
          command: npm install
      - run:
        name: run test
        command: npm test
       
