version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 
          name: Install dependencies
          commands: |
            npm install
      - run:
          name: Run tests
          commands: |
            npm test